prefix 'reset_changed' and 'flag_changed' with underscore. implement '_failure_reason' and '_define'.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -27,16 +27,31 @@ shopt -s nullglob
 
 #absolute path to the directory of this script
 readonly _SCRIPT_DIR="$( cd "$(dirname "$0")" && pwd -P )" || exit 1
-_dry_run=0    #perform a trial run with no changes made if this is true
-_verbose=0    #show the action that made no change if this is true
-_script_name= #name of currely running script
-_changed=0    #whether last action was changed the system or not
+
+if [[ -t 1 ]]; then
+    readonly _COLOR_FAILED=$(tput setaf 1) || exit 1  #red
+    readonly _COLOR_OK=$(tput setaf 2) || exit 1      #green
+    readonly _COLOR_CHANGED=$(tput setaf 3) || exit 1 #yellow
+    readonly _COLOR_RESET=$(tput sgr0) || exit 1
+    readonly _ERASE_TO_EOL=$(tput el) || exit 1
+else
+    readonly _COLOR_FAILED=
+    readonly _COLOR_OK=
+    readonly _COLOR_CHANGED=
+    readonly _COLOR_RESET=
+    readonly _ERASE_TO_EOL=
+fi
+
+_dry_run=0       #perform a trial run with no changes made if this is true
+_verbose=0       #show the action that made no change if this is true
+_script_name=    #name of currely running script
+_changed=0       #whether last action was changed the system or not
 
 is_dry_run() {
     (( _dry_run ))
 }
 
-reset_changed() {
+_reset_changed() {
     _changed=0
 }
 
@@ -44,8 +59,47 @@ is_changed() {
     (( _changed ))
 }
 
-flag_changed() {
+_flag_changed() {
     _changed=1
+}
+
+_failure_reason() {
+    [[ -t 1 ]] && echo -n "$_ERASE_TO_EOL"
+    echo "$*" >&2
+}
+
+# define function $1 which calls $2 and show its progress
+_define() {
+    if (( $# != 2 )); then
+        echo "Wrong number of arguments" >&2
+        return 1
+    fi
+
+    local action_quoted=$(printf "$1")
+    local impl_quoted=$2
+
+    eval "
+$action_quoted() {
+    _reset_changed
+    [[ -t 1 ]] && echo -n \"           \$_script_name: $action_quoted $\*\"\$'\r'
+
+    if ! $impl_quoted \"\$@\"; then
+        echo \"[ \${_COLOR_FAILED}FAILED\${_COLOR_RESET} ] \$_script_name: $action_quoted \$*\"
+        exit 1
+    fi
+
+    if is_changed; then
+        echo \"[\${_COLOR_CHANGED}CHANGED\${_COLOR_RESET} ] \$_script_name: $action_quoted \$*\"
+        return 0
+    fi
+
+    echo -n \"[   \${_COLOR_OK}OK\${_COLOR_RESET}   ] \$_script_name: $action_quoted \$*\"
+    [[ -t 1 ]] && (( ! _verbose )) && echo -n \$'\r' || echo
+
+    return 0
+}"
+
+    return 0
 }
 
 for _lib in "$_SCRIPT_DIR"/lib/*.sh; do
